version: '3.8'

services:
  # Base de Datos
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432"

  # Servicio de Django
  web_django:
    build: ./django_core
    # Este comando espera a la DB, migra y arranca
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django_core:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  # Servicio de FastAPI
  ai_processor:
    build: ./fastapi_service
    volumes:
      - ./fastapi_service:/app
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - web_django

volumes:
  postgres_data: